- hosts: master-01
  become: yes
  become_user: centos
  gather_facts: false
  tasks:      
    - name: Install cert-manager
      shell: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install \
            cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version v1.11.0 \
            --set installCRDs=true