- hosts: all, !lb
  become: yes
  tasks:
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Disable SELinux
      command: setenforce 0

    - name: Disable SELinux on reboot
      selinux:
        state: disabled

    - name: Enable transparent masquerading and facilitate Virtual Extensible LAN (VxLAN) traffic for communication between Kubernetes pods across the cluster
      command: modprobe br_netfilter

    - name: Ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        state: present

    - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present

    - name: Ensure net.ipv4.ip_forward is set to 1
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Install Docker
      yum:
        name: docker
        state: present
        update_cache: true

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Add Kubernetes YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes

    - name: Install kubelet
      yum:
          name: kubelet-1.22.2
          state: present
          update_cache: true
          allow_downgrade: yes

    - name: Install kubeadm
      yum:
          name: kubeadm-1.22.2
          state: present
          allow_downgrade: yes

    - name: Start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started

- hosts: masters
  become: yes
  tasks:
    - name: Install kubectl
      yum:
          name: kubectl-1.22.0
          state: present
          allow_downgrade: yes