- hosts: master-01
  become: yes
  become_user: centos
  gather_facts: false
  tasks:      
    - name: Add the metrics-server repo to Helm repository
      shell: |
        helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
        helm repo update

    - name: Install metrics-server
      shell: |
        helm upgrade --install metrics-server metrics-server/metrics-server --namespace kube-system
        kubectl patch deployment metrics-server -n kube-system --type 'json' -p '[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--kubelet-insecure-tls"}]'