- hosts: master-01
  become: yes
  gather_facts: no
  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Debug
      debug:
        msg={{ join_command }}

- hosts: workers
  become: yes
  gather_facts: no
  tasks:
    - name: Join to cluster
      command: "{{ hostvars['master-01']['join_command'] }} --ignore-preflight-errors all"