name:  CI-CD
run-name: ${{ github.actor }} is running out GitHub Actions 🚀
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/LICENSE'
      - 'ansible/**'
      - 'kubernetes-manifests/**'
      
jobs:
  build:
    if: ${{ true }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      sha_short: ${{ steps.checkout.outputs.sha_short }}
    steps:
      - name: Install a chart
        run: |
          mkdir ~/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/.kube/config
          export KUBECONFIG=~/.kube/config

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Define sha_short
        id: checkout
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/viastakhov/loadgenerator
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{steps.checkout.outputs.sha_short}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push an image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:src/loadgenerator"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./helm  
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
          
      - name: Install a chart
        run: |
          mkdir ~/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/.kube/config
          export KUBECONFIG=~/.kube/config
          helm upgrade --install loadgenerator . --set image.tag=${{needs.build.outputs.sha_short}} --namespace default

